import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Shared/Footer";
import Header from "@/components/Shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="lg:w-[1200px] mx-auto bg-white">
          <Header />
        </div>
        <div className="lg:w-[1200px] mx-auto bg-white">{children}</div>
        <div className="w-full h-screen md:h-96 bg-[#EFE2DA] grid items-center justify-center rounded-md my-5">
          <div className="max-w-[1200px] h-56 bg-white gap-4 grid items-center grid-cols-1 md:grid-cols-2 py-3 md:py-0 px-10">
            <div>
              <h1 className="text-2xl font-semibold">
                Like our service? Subscribe us
              </h1>
              <h1 className="text-xl">
              We have more than thousand of creative entrepreneurs and stat joining our business
              </h1>
            </div>
            <form>
              <label
                for="default-search"
                class="mb-2 text-sm font-medium text-gray-900 sr-only"
              >
                Search
              </label>
              <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <svg
                    class="w-4 h-4 text-gray-500 dark:text-gray-400"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 20 20"
                  >
                    <path
                      stroke="currentColor"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                    />
                  </svg>
                </div>
                <input
                  type="search"
                  id="default-search"
                  class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Search Mockups, Logos..."
                  required
                />
                <button
                  type="submit"
                  class="text-white absolute right-2.5 bottom-2.5 bg-[#0A8080] hover:bg-[#0b6e6e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2"
                >
                  Search
                </button>
              </div>
            </form>
          </div>
        </div>
        <div className="lg:w-[1200px] mx-auto bg-white">
          <Footer />
        </div>
      </body>
    </html>
  );
}
